service: c5-zhiyong-i
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  firstfunction:
    handler: index.firsthandler
    events:
      - httpApi:
          path: /zyget
          method: get

  secondfunction:
    handler: index.secondhandler
    events:
      - httpApi:
          path: /zypost
          method: post

plugins:
  - serverless-offline