service: c5-zhiyong-i
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  deploymentBucket:
    name: cohort5.deployment

functions:
  firstfunction:
    handler: index.firsthandler
    events:
      - httpApi:
          path: /zyget
          method: get
      - sqs:
          arn: arn:aws:sqs:us-east-1:255945442255:zhiyong-serverless-sqs

  secondfunction:
    handler: index.secondhandler
    events:
      - httpApi:
          path: /zypost
          method: post
      - sqs:
          arn:
            Fn::GetAtt:
              - ZhiyongQueue
              - Arn

resources:
  Resources:
    ZhiyongQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "zhiyong-queue"

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-offline